"""Stage 88: TextbookPromoter — persist verified death hypotheses across generations.

A DeathHypothesis is promoted when it has accumulated enough evidence:
    support_rate >= 0.5 AND n_observed >= 5

Promoted hypotheses are saved to configs/promoted_hypotheses.yaml and loaded
at the start of each new generation so the agent does not re-discover
what prior generations already learned.

Design: docs/superpowers/specs/2026-04-15-stage88-textbook-promotion-design.md
"""

from __future__ import annotations

from pathlib import Path

import yaml

from snks.agent.death_hypothesis import DeathHypothesis

PROMOTE_SUPPORT_RATE = 0.5
PROMOTE_MIN_OBSERVED = 5


class TextbookPromoter:
    """Read/write promotable death hypotheses to a YAML store.

    Usage (per generation):
        promoter = TextbookPromoter()
        promoted = promoter.load(path)          # start of gen
        ...run episodes...
        to_promote = [h for h in tracker.all_hypotheses() if promoter.should_promote(h)]
        promoter.save(to_promote, path)         # end of gen
    """

    def should_promote(self, h: DeathHypothesis) -> bool:
        """Return True if h meets the promotion threshold."""
        return h.support_rate >= PROMOTE_SUPPORT_RATE and h.n_observed >= PROMOTE_MIN_OBSERVED

    def load(self, path: Path) -> list[DeathHypothesis]:
        """Load promoted hypotheses from YAML. Returns [] if file absent or empty."""
        if not path.exists():
            return []
        data = yaml.safe_load(path.read_text()) or {}
        entries = data.get("hypotheses") or []
        return [
            DeathHypothesis(
                cause=e["cause"],
                vital=e["vital"],
                threshold=float(e["threshold"]),
                n_supporting=int(e["n_supporting"]),
                n_observed=int(e["n_observed"]),
            )
            for e in entries
        ]

    def save(self, hypotheses: list[DeathHypothesis], path: Path) -> None:
        """Write promotable hypotheses to YAML, merging with existing entries.

        Merge logic: for each (cause, vital) key, keep the entry with the
        higher n_observed (richer observation wins).
        """
        existing = self.load(path)
        merged: dict[tuple, DeathHypothesis] = {
            (h.cause, h.vital): h for h in existing
        }
        for h in hypotheses:
            key = (h.cause, h.vital)
            if key not in merged or h.n_observed > merged[key].n_observed:
                merged[key] = h

        entries = [
            {
                "cause": h.cause,
                "vital": h.vital,
                "threshold": float(h.threshold),
                "n_supporting": int(h.n_supporting),
                "n_observed": int(h.n_observed),
            }
            for h in sorted(merged.values(), key=lambda h: (h.cause, h.vital))
        ]

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Auto-generated by TextbookPromoter. Do not edit manually.\n"
            + yaml.dump({"hypotheses": entries}, default_flow_style=False)
        )
