"""Helpers for promoting durable experience into declarative YAML stores.

Stage 88 introduced a narrow death-hypothesis YAML store used by the
post-mortem curiosity loop. The current promoter keeps that legacy path
working while adding a schema-versioned node store for newer promotion
iterations such as persistent entity observations.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from snks.agent.death_hypothesis import DeathHypothesis

PROMOTE_SUPPORT_RATE = 0.5
PROMOTE_MIN_OBSERVED = 5
PROMOTED_SCHEMA_VERSION = 1
PROMOTABLE_ENTITIES = frozenset({"table", "furnace"})

PromotedNode = dict[str, Any]


def _node_key(node: PromotedNode) -> tuple[Any, ...] | None:
    """Return the merge key for schema-v1 nodes, or None if unsupported."""
    node_type = node.get("type")
    body = node.get("body")
    if not isinstance(body, dict):
        return None
    concept = body.get("concept")
    position = body.get("position")
    if not isinstance(position, list) or len(position) != 2:
        return None
    return (node_type, concept, int(position[0]), int(position[1]))


def _legacy_hypothesis_entries(data: object) -> list[dict[str, Any]]:
    """Extract Stage 88 hypothesis entries from a legacy YAML payload."""
    if not isinstance(data, dict):
        return []
    entries = data.get("hypotheses")
    return list(entries) if isinstance(entries, list) else []


class TextbookPromoter:
    """Read/write promotable knowledge in legacy and schema-v1 formats."""

    def should_promote(self, h: DeathHypothesis) -> bool:
        """Return True if h meets the promotion threshold."""
        return h.support_rate >= PROMOTE_SUPPORT_RATE and h.n_observed >= PROMOTE_MIN_OBSERVED

    def load(self, path: Path) -> list[DeathHypothesis]:
        """Load Stage 88 promoted hypotheses from YAML.

        Legacy callers still expect `list[DeathHypothesis]`. Schema-v1 node
        stores simply return an empty list here.
        """
        if not path.exists():
            return []
        data = yaml.safe_load(path.read_text()) or {}
        entries = _legacy_hypothesis_entries(data)
        return [
            DeathHypothesis(
                cause=e["cause"],
                vital=e["vital"],
                threshold=float(e["threshold"]),
                n_supporting=int(e["n_supporting"]),
                n_observed=int(e["n_observed"]),
            )
            for e in entries
        ]

    def save(self, hypotheses: list[DeathHypothesis], path: Path) -> None:
        """Write Stage 88 promotable hypotheses to a legacy YAML store.

        Merge logic: for each (cause, vital) key, keep the entry with the
        higher n_observed (richer observation wins).
        """
        existing = self.load(path)
        merged: dict[tuple, DeathHypothesis] = {
            (h.cause, h.vital): h for h in existing
        }
        for h in hypotheses:
            key = (h.cause, h.vital)
            if key not in merged or h.n_observed > merged[key].n_observed:
                merged[key] = h

        entries = [
            {
                "cause": h.cause,
                "vital": h.vital,
                "threshold": float(h.threshold),
                "n_supporting": int(h.n_supporting),
                "n_observed": int(h.n_observed),
            }
            for h in sorted(merged.values(), key=lambda h: (h.cause, h.vital))
        ]

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Auto-generated by TextbookPromoter. Do not edit manually.\n"
            + yaml.dump({"hypotheses": entries}, default_flow_style=False)
        )

    def load_nodes(self, path: Path) -> list[PromotedNode]:
        """Load schema-v1 promoted nodes. Legacy hypothesis stores yield []."""
        if not path.exists():
            return []
        data = yaml.safe_load(path.read_text()) or {}
        if not isinstance(data, dict):
            return []
        if int(data.get("schema_version", 0) or 0) != PROMOTED_SCHEMA_VERSION:
            return []
        nodes = data.get("nodes")
        return list(nodes) if isinstance(nodes, list) else []

    def save_nodes(self, nodes: list[PromotedNode], path: Path) -> None:
        """Write schema-v1 promoted nodes."""
        payload = {
            "schema_version": PROMOTED_SCHEMA_VERSION,
            "nodes": nodes,
        }
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Auto-generated by TextbookPromoter. Do not edit manually.\n"
            + yaml.dump(payload, default_flow_style=False, sort_keys=False)
        )

    def collect_entity_observations(
        self,
        spatial_map: Any,
        episode_index: int,
    ) -> list[PromotedNode]:
        """Compile stable placed-object observations from a spatial map."""
        nodes: list[PromotedNode] = []
        map_data = getattr(spatial_map, "_map", {})
        if not isinstance(map_data, dict):
            return nodes

        for (y, x), entry in sorted(map_data.items()):
            if not isinstance(entry, tuple) or len(entry) != 3:
                continue
            concept, confidence, count = entry
            if concept not in PROMOTABLE_ENTITIES or int(count) < 2:
                continue
            nodes.append({
                "type": "entity_observation",
                "body": {
                    "concept": str(concept),
                    "position": [int(y), int(x)],
                },
                "provenance": {
                    "source": "spatial_map_compiler",
                    "observation_count": int(count),
                    "observed_in_episodes": 1,
                    "first_seen_episode": int(episode_index),
                    "last_seen_episode": int(episode_index),
                    "confidence": float(confidence),
                },
            })
        return nodes

    def merge_nodes(
        self,
        prior_nodes: list[PromotedNode],
        new_nodes: list[PromotedNode],
    ) -> list[PromotedNode]:
        """Merge current-episode node observations into prior schema-v1 nodes."""
        merged: dict[tuple[Any, ...], PromotedNode] = {}
        passthrough: list[PromotedNode] = []

        for node in prior_nodes:
            key = _node_key(node)
            if key is None:
                passthrough.append(node)
                continue
            merged[key] = {
                "type": node["type"],
                "body": dict(node["body"]),
                "provenance": dict(node.get("provenance", {})),
            }

        for node in new_nodes:
            key = _node_key(node)
            if key is None:
                passthrough.append(node)
                continue
            provenance = dict(node.get("provenance", {}))
            if key not in merged:
                merged[key] = {
                    "type": node["type"],
                    "body": dict(node["body"]),
                    "provenance": provenance,
                }
                continue
            dst = merged[key]["provenance"]
            dst["source"] = provenance.get("source", dst.get("source", "spatial_map_compiler"))
            dst["observation_count"] = int(dst.get("observation_count", 0)) + int(
                provenance.get("observation_count", 0)
            )
            dst["observed_in_episodes"] = int(dst.get("observed_in_episodes", 0)) + int(
                provenance.get("observed_in_episodes", 1)
            )
            dst["first_seen_episode"] = min(
                int(dst.get("first_seen_episode", provenance.get("first_seen_episode", 0))),
                int(provenance.get("first_seen_episode", dst.get("first_seen_episode", 0))),
            )
            dst["last_seen_episode"] = max(
                int(dst.get("last_seen_episode", provenance.get("last_seen_episode", 0))),
                int(provenance.get("last_seen_episode", dst.get("last_seen_episode", 0))),
            )
            dst["confidence"] = max(
                float(dst.get("confidence", 0.0)),
                float(provenance.get("confidence", 0.0)),
            )

        merged_nodes = sorted(
            merged.values(),
            key=lambda node: (
                str(node.get("type", "")),
                str(node.get("body", {}).get("concept", "")),
                int(node.get("body", {}).get("position", [0, 0])[0]),
                int(node.get("body", {}).get("position", [0, 0])[1]),
            ),
        )
        return passthrough + merged_nodes
